name: .NET Core

on:
  push:
    branches: [ feature/*, bugfix/*, hotfix/* ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.404
    - name: Restore ca-sln
      run: dotnet restore './templates/ca-sln/_APP_NAME_.sln'
    - name: Build ca-sln
      run: dotnet build './templates/ca-sln/_APP_NAME_.sln' --configuration Release --no-restore
    - name: Test ca-sln
      run: dotnet test './templates/ca-sln/_APP_NAME_.sln' --no-restore --verbosity minimal
